// Copyright (C) 1991-2014 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 14.0 (Build Build 200 06/17/2014)
// Created on Mon Jun 08 16:49:52 2015

TERAISC_PWM_EX TERAISC_PWM_EX_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.s_cs(s_cs_sig) ,	// input  s_cs_sig
	.s_address(s_address_sig) ,	// input [1:0] s_address_sig
	.s_write(s_write_sig) ,	// input  s_write_sig
	.s_writedata(s_writedata_sig) ,	// input [31:0] s_writedata_sig
	.s_read(s_read_sig) ,	// input  s_read_sig
	.s_readdata(s_readdata_sig) ,	// output [31:0] s_readdata_sig
	.PWM(PWM_sig) 	// output  PWM_sig
);

